# Generated by Django 4.0.6 on 2022-07-18 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imag',
            new_name='image',
        ),
    ]
